### ISSUE TITLE
Redesign Throb Counting

### ISSUE THREAD

**Issue by BobbyU** [BobbyU/IRC-Parser#8]
Right now the throb counting is designed poorly, and will only count one throb per talk.

This should be changed to have the ability to count any number of throbs per line.

**Comment by jmansfieldTF** [comment]
wouldn't this be really easy to implement by parsing through the entire document and finding any string that was 'throb' of course with some type of exception for usernames

**Comment by BobbyU** [comment]
yeah it would be, although that's pretty inefficient...
